import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import{Plus,Search,CheckCircle2,Inbox,CalendarDays,BarChart3,Target,Moon,Sun,Archive,LogOut,Cloud,Trash2,Play,Pause,X,LayoutGrid,List,Check}from'lucide-react';
import'./styles.css';
const supabase=import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_ANON_KEY?createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY):null;
const id=()=>crypto.randomUUID(),today=()=>new Date().toISOString().slice(0,10);
const seed=[{id:id(),title:'Finish homepage redesign',project:'Design',priority:1,due:today(),status:'todo',estimate:90,notes:'Polish responsive states and prepare handoff.',labels:['Design'],repeat:null},{id:id(),title:'Review product analytics',project:'Product',priority:2,due:today(),status:'doing',estimate:30,notes:'Check onboarding drop-off.',labels:['Research'],repeat:null},{id:id(),title:'Plan next week',project:'Personal',priority:3,due:today(),status:'todo',estimate:20,notes:'Block deep work time.',labels:['Planning'],repeat:'weekly'},{id:id(),title:'Read 20 pages',project:'Personal',priority:4,due:null,status:'done',estimate:25,notes:'',labels:['Learning'],repeat:'daily'}];
function App(){
const[session,setSession]=useState(null),[tasks,setTasks]=useState(seed),[view,setView]=useState('today'),[q,setQ]=useState(''),[dark,setDark]=useState(false),[selected,setSelected]=useState(null),[focus,setFocus]=useState(false),[seconds,setSeconds]=useState(1500),[auth,setAuth]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState('');
useEffect(()=>{document.documentElement.className=dark?'dark':''},[dark]);
useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(x=>setSession(x.data.session));const{data}=supabase.auth.onAuthStateChange((_,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!session||!supabase)return;load();const c=supabase.channel('tasks').on('postgres_changes',{event:'*',schema:'public',table:'tasks',filter:`user_id=eq.${session.user.id}`},load).subscribe();return()=>supabase.removeChannel(c)},[session]);
useEffect(()=>{if(!focus)return;const t=setInterval(()=>setSeconds(s=>s<=1?(setFocus(false),1500):s-1),1000);return()=>clearInterval(t)},[focus]);
async function load(){const{data}=await supabase.from('tasks').select('*').order('created_at',{ascending:false});if(data)setTasks(data)}
async function persist(t){setTasks(x=>x.map(a=>a.id===t.id?t:a));if(session)await supabase.from('tasks').upsert({...t,user_id:session.user.id})}
async function add(){const title=prompt('Task name');if(!title)return;const t={id:id(),title,project:'Inbox',priority:4,due:today(),status:'todo',estimate:30,notes:'',labels:[],repeat:null};setTasks(x=>[t,...x]);if(session)await supabase.from('tasks').insert({...t,user_id:session.user.id})}
async function remove(t){setTasks(x=>x.filter(a=>a.id!==t.id));if(session)await supabase.from('tasks').delete().eq('id',t.id);setSelected(null)}
async function login(e){e.preventDefault();if(!supabase)return alert('Add Supabase environment variables first.');let r=await supabase.auth.signInWithPassword({email,password});if(r.error){r=await supabase.auth.signUp({email,password});if(r.error)alert(r.error.message)}setAuth(false)}
const visible=useMemo(()=>tasks.filter(t=>(!q||(t.title+' '+t.project+' '+t.labels).toLowerCase().includes(q.toLowerCase()))&&(view==='today'?(t.due===today()||t.status==='done'):view==='inbox'?t.project==='Inbox':view==='upcoming'?t.due&&t.due>=today():view==='completed'?t.status==='done':view.startsWith('project:')?t.project===view.slice(8):true)),[tasks,q,view]);
const open=tasks.filter(t=>t.status!=='done').length,done=tasks.filter(t=>t.status==='done').length;
const nav=[['today','Today',CheckCircle2],['inbox','Inbox',Inbox],['upcoming','Upcoming',CalendarDays],['completed','Completed',Archive]];
const label=view==='today'?'Today':view==='inbox'?'Inbox':view==='upcoming'?'Upcoming':view==='completed'?'Completed':view.startsWith('project:')?view.slice(8):view[0].toUpperCase()+view.slice(1);
return <div className="app"><aside><div className="brand"><b>✓</b><strong>TaskFlow</strong><small>PRO</small></div><button className="add"onClick={add}><Plus size={16}/> Add task</button>{nav.map(([v,l,I])=><button className={'nav '+(view===v?'active':'')}onClick={()=>setView(v)}><I size={17}/>{l}<span>{v==='today'?open:''}</span></button>)}<div className="section">WORKSPACES</div>{['Design','Product','Personal'].map(p=><button className="nav"onClick={()=>setView('project:'+p)}><i className={'dot '+p.toLowerCase()}/>{p}</button>)}<div className="section">TOOLS</div><button className="nav"onClick={()=>setView('calendar')}><CalendarDays size={17}/>Calendar</button><button className="nav"onClick={()=>setView('analytics')}><BarChart3 size={17}/>Analytics</button><button className="nav"onClick={()=>setView('focus')}><Target size={17}/>Focus</button><div className="bottom"><button className="nav"onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}Appearance</button>{session?<button className="nav"onClick={()=>supabase.auth.signOut()}><LogOut size={17}/>Sign out</button>:<button className="nav"onClick={()=>setAuth(true)}><Cloud size={17}/>Cloud sync</button>}</div></aside><main><header><b>My workspace / {label}</b><div className="search"><Search size={15}/><input value={q}onChange={e=>setQ(e.target.value)}placeholder="Search tasks..."/></div><button className="theme"onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button></header><section className="content">{view==='calendar'?<Calendar tasks={tasks}/>:view==='analytics'?<Analytics tasks={tasks}/>:view==='focus'?<Focus seconds={seconds}focus={focus}setFocus={setFocus}/>:<><div className="head"><div><small>TASK MANAGEMENT</small><h1>{label}</h1><p>{open} open tasks · {done} completed</p></div><button className="primary"onClick={add}><Plus size={15}/> New task</button></div><div className="toolbar"><span>{visible.length} tasks</span><button onClick={()=>{}}> <List size={14}/> List</button></div><div className="tasks">{visible.length?visible.map(t=><Task key={t.id}t={t}onClick={()=>setSelected(t)}onDone={()=>persist({...t,status:t.status==='done'?'todo':'done'})}/>):<div className="empty"><CheckCircle2 size={35}/><h3>Nothing here</h3><p>Your task list is clear.</p></div>}</div></>}</section></main>{selected&&<Drawer t={selected}save={persist}remove={remove}close={()=>setSelected(null)}/>} {auth&&<div className="overlay"><form className="auth"onSubmit={login}><button className="close"onClick={()=>setAuth(false)}type="button"><X/></button><div className="logo">✓</div><h2>Cloud sync</h2><p>Sign in or create an account to keep tasks synced across devices.</p><input required type="email"placeholder="Email"value={email}onChange={e=>setEmail(e.target.value)}/><input required minLength="6"type="password"placeholder="Password"value={password}onChange={e=>setPassword(e.target.value)}/><button className="primary full">Continue</button></form></div>}</div>}
function Task({t,onClick,onDone}){return <div className="task"onClick={onClick}><button className={'check '+(t.status==='done'?'done':'')}onClick={e=>(e.stopPropagation(),onDone())}>{t.status==='done'&&<Check size={13}/>}</button><div className="taskbody"><strong className={t.status==='done'?'strike':''}>{t.title}</strong><small>{t.project} · {t.due||'No date'} · {t.estimate} min</small></div><em className={'p p'+t.priority}>P{t.priority}</em></div>}
function Drawer({t,save,remove,close}){const[x,setX]=useState(t);return <div className="overlay"><div className="drawer"><header><b>Task details</b><button onClick={close}><X/></button></header><div className="drawerbody"><input className="title" value={x.title}onChange={e=>setX({...x,title:e.target.value})}/><div className="grid"><label>Project<input value={x.project}onChange={e=>setX({...x,project:e.target.value})}/></label><label>Due date<input type="date"value={x.due||''}onChange={e=>setX({...x,due:e.target.value||null})}/></label><label>Priority<select value={x.priority}onChange={e=>setX({...x,priority:+e.target.value})}>{[1,2,3,4].map(n=><option value={n}>Priority {n}</option>)}</select></label><label>Estimate<input type="number"value={x.estimate}onChange={e=>setX({...x,estimate:+e.target.value})}/></label></div><label className="notes">Notes<textarea value={x.notes}onChange={e=>setX({...x,notes:e.target.value})}/></label><label className="notes">Repeat<select value={x.repeat||''}onChange={e=>setX({...x,repeat:e.target.value||null})}><option value="">Does not repeat</option><option>daily</option><option>weekly</option><option>monthly</option></select></label></div><footer><button className="danger"onClick={()=>remove(x)}><Trash2 size={15}/> Delete</button><button className="primary"onClick={()=>{save(x);close()}}>Save changes</button></footer></div></div>}
function Calendar({tasks}){const d=new Date(),start=new Date(d.getFullYear(),d.getMonth(),1),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),cells=Array.from({length:start.getDay()+days},(_,i)=>i<start.getDay()?null:i-start.getDay()+1);return <div className="page"><small>PLANNING</small><h1>Calendar</h1><div className="cal">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><b>{x}</b>)}{cells.map(day=><div>{day&&<><span>{day}</span>{tasks.filter(t=>t.due===`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`).map(t=><label>{t.title}</label>)}</>}</div>)}</div></div>}
function Analytics({tasks}){return <div className="page"><small>INSIGHTS</small><h1>Analytics</h1><p>Simple productivity overview.</p><div className="metrics"><div><span>Open</span><strong>{tasks.filter(t=>t.status!=='done').length}</strong></div><div><span>Completed</span><strong>{tasks.filter(t=>t.status==='done').length}</strong></div><div><span>Estimated minutes</span><strong>{tasks.reduce((a,t)=>a+t.estimate,0)}</strong></div><div><span>Projects</span><strong>{new Set(tasks.map(t=>t.project)).size}</strong></div></div></div>}
function Focus({seconds,focus,setFocus}){return <div className="page"><small>DEEP WORK</small><h1>Focus</h1><p>Pomodoro timer</p><div className="focus"><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><button className="primary"onClick={()=>setFocus(!focus)}>{focus?<Pause/>:<Play/>}{focus?'Pause':'Start'}</button><button onClick={()=>setFocus(false)}>Reset</button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);